public enum GameState_Enum
{
    START,
    
    FADE_LIGHTS_IN,
    LIGHTS_ON,
    
    AWAITING_PLAYER_APPROACH,
    PLAYER_APPROACHED,
    
    AWAITING_PLAYER_DECISION,
    PLAYER_DECISION,
    
    AWAITING_PLAYER_RETURN,
    PLAYER_RETURNED,
    
    FADE_LIGHTS_OUT,
    LIGHTS_OFF,
    
    AWAITING_PLAYER_RESULTS,
    PLAYER_RESULTS_COLLECTED,
    
    CHECK_END
}
